SELECT A.PRODUCT_ID, A.PRODUCT_NAME, SUM(B.AMOUNT * A.PRICE) AS SUM
  FROM FOOD_PRODUCT A
      ,FOOD_ORDER B
 WHERE 1=1
   AND A.PRODUCT_ID = B.PRODUCT_ID
   AND TO_CHAR(B.PRODUCE_DATE, 'YYYYMM') = '202205'
GROUP BY A.PRODUCT_ID, A.PRODUCT_NAME
ORDER BY SUM DESC, A.PRODUCT_ID ASC