SELECT A.CATEGORY, A.PRICE, A.PRODUCT_NAME
  FROM FOOD_PRODUCT A,
      (SELECT PRODUCT_CD,
             RANK() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS RANK
        FROM FOOD_PRODUCT
       WHERE 1=1
         AND CATEGORY IN ('과자', '국', '김치', '식용유')
      ) B
 WHERE 1=1
   AND A.PRODUCT_CD = B.PRODUCT_CD
   AND B.RANK = 1
ORDER BY A.PRICE DESC